-- Added check to see if libtool is installed and, if not, shout when    oomph-lib needs reconfiguring, e.g. after adding a directory    somewhere; this can only be done when libtool is available!    Now bails out more gracefully.
-- Add instructions to autogen.sh to explain how to customise
   configure options (now that the command-line-based version is gone).

-- Added machinery to check for request to build trilinos with dynamic
   linking flags (by pre-scanning configure options file). We're now
   only adding -fPIC and -DPIC if they're actually needed to avoid
   any portability problems if the default (static) build is used.
   Machinery is a bit clunky because the grep command hung when
   executed directly in non_interactive_autogen.sh. Moved that bit
   into a separate script.

-- Tidied up many demo driver codes that died following Christian's
   (very sensible!) decision to turn the FE::output(...) function
   into a properly broken virtual one. Problems arose typically
   when meshes contained multiple element types (and why would
   anybody write code like that; not naming any names...).
   Validata had to be tidied up to remove the (stupid) default
   output that we created in the non-broken version.

-- Added a soluble_surfactant_transport_equations.h to the
   dependencies in two_layer_soluble_surfactant code, otherwise it
   doesn't get shipped with tar file and causes the compilation
   of the self test to fail.

-- Added a missing "n" in the Makefile.am for cgal. Now the default
   installation does get wiped when doing a make distclean :)




git-svn-id: svn+ssh://vummath.ma.man.ac.uk/home/svn-oomphlib/public/trunk@1343 595e1d82-adf1-4282-bac7-b6073fa2ca8e

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -128,3 +128,28 @@ do-we-have-mpi:
 
 
 
+# Check if we have libtool installed (needed for updating
+# distribution when new directories are added etc.)
+check_if_we_have_have_libtool_installed_and_say_that_we_cant_reconfigure_if_not:
+	@if $(have_libtool); then \
+            echo "Have libtool so can reconfigure oomph-lib"; \
+            echo "e.g. after adding new directories."; \
+            exit 0; \
+        else \
+            echo " "; \
+            echo " "; \
+            echo "==================================================="; \
+            echo " "; \
+            echo " "; \
+            echo " "; \
+            echo "Don't have libtool so we can't reconfigure oomph-lib"; \
+            echo "e.g. after adding new directories. Please install it"; \
+            echo "and re-run autogen.sh!"; \
+            echo " "; \
+            echo " "; \
+            echo " "; \
+            echo "==================================================="; \
+            echo " "; \
+            echo " "; \
+            exit 1; \
+        fi;
